//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RF.VehicleTracker.UIService.ModelReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CModel", Namespace="http://schemas.datacontract.org/2004/07/RF.VehicleTracker.BL")]
    [System.SerializableAttribute()]
    public partial class CModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ModelReference.IModel")]
    public interface IModel {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModel/GetModels", ReplyAction="http://tempuri.org/IModel/GetModelsResponse")]
        System.Collections.Generic.List<RF.VehicleTracker.UIService.ModelReference.CModel> GetModels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModel/GetModels", ReplyAction="http://tempuri.org/IModel/GetModelsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<RF.VehicleTracker.UIService.ModelReference.CModel>> GetModelsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModel/Insert", ReplyAction="http://tempuri.org/IModel/InsertResponse")]
        void Insert(string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModel/Insert", ReplyAction="http://tempuri.org/IModel/InsertResponse")]
        System.Threading.Tasks.Task InsertAsync(string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModel/Update", ReplyAction="http://tempuri.org/IModel/UpdateResponse")]
        void Update(System.Guid id, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModel/Update", ReplyAction="http://tempuri.org/IModel/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(System.Guid id, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModel/Delete", ReplyAction="http://tempuri.org/IModel/DeleteResponse")]
        void Delete(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModel/Delete", ReplyAction="http://tempuri.org/IModel/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModel/GetById", ReplyAction="http://tempuri.org/IModel/GetByIdResponse")]
        RF.VehicleTracker.UIService.ModelReference.CModel GetById(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModel/GetById", ReplyAction="http://tempuri.org/IModel/GetByIdResponse")]
        System.Threading.Tasks.Task<RF.VehicleTracker.UIService.ModelReference.CModel> GetByIdAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModel/UpdateObj", ReplyAction="http://tempuri.org/IModel/UpdateObjResponse")]
        void UpdateObj(RF.VehicleTracker.UIService.ModelReference.CModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModel/UpdateObj", ReplyAction="http://tempuri.org/IModel/UpdateObjResponse")]
        System.Threading.Tasks.Task UpdateObjAsync(RF.VehicleTracker.UIService.ModelReference.CModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModel/DeleteObj", ReplyAction="http://tempuri.org/IModel/DeleteObjResponse")]
        void DeleteObj(RF.VehicleTracker.UIService.ModelReference.CModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModel/DeleteObj", ReplyAction="http://tempuri.org/IModel/DeleteObjResponse")]
        System.Threading.Tasks.Task DeleteObjAsync(RF.VehicleTracker.UIService.ModelReference.CModel model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IModelChannel : RF.VehicleTracker.UIService.ModelReference.IModel, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModelClient : System.ServiceModel.ClientBase<RF.VehicleTracker.UIService.ModelReference.IModel>, RF.VehicleTracker.UIService.ModelReference.IModel {
        
        public ModelClient() {
        }
        
        public ModelClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModelClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<RF.VehicleTracker.UIService.ModelReference.CModel> GetModels() {
            return base.Channel.GetModels();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<RF.VehicleTracker.UIService.ModelReference.CModel>> GetModelsAsync() {
            return base.Channel.GetModelsAsync();
        }
        
        public void Insert(string description) {
            base.Channel.Insert(description);
        }
        
        public System.Threading.Tasks.Task InsertAsync(string description) {
            return base.Channel.InsertAsync(description);
        }
        
        public void Update(System.Guid id, string description) {
            base.Channel.Update(id, description);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(System.Guid id, string description) {
            return base.Channel.UpdateAsync(id, description);
        }
        
        public void Delete(System.Guid id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(System.Guid id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public RF.VehicleTracker.UIService.ModelReference.CModel GetById(System.Guid id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<RF.VehicleTracker.UIService.ModelReference.CModel> GetByIdAsync(System.Guid id) {
            return base.Channel.GetByIdAsync(id);
        }
        
        public void UpdateObj(RF.VehicleTracker.UIService.ModelReference.CModel model) {
            base.Channel.UpdateObj(model);
        }
        
        public System.Threading.Tasks.Task UpdateObjAsync(RF.VehicleTracker.UIService.ModelReference.CModel model) {
            return base.Channel.UpdateObjAsync(model);
        }
        
        public void DeleteObj(RF.VehicleTracker.UIService.ModelReference.CModel model) {
            base.Channel.DeleteObj(model);
        }
        
        public System.Threading.Tasks.Task DeleteObjAsync(RF.VehicleTracker.UIService.ModelReference.CModel model) {
            return base.Channel.DeleteObjAsync(model);
        }
    }
}
