//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RF.VehicleTracker.UIService.ColorReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CColor", Namespace="http://schemas.datacontract.org/2004/07/RF.VehicleTracker.BL")]
    [System.SerializableAttribute()]
    public partial class CColor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ColorReference.IColor")]
    public interface IColor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColor/InsertObj", ReplyAction="http://tempuri.org/IColor/InsertObjResponse")]
        void InsertObj(RF.VehicleTracker.UIService.ColorReference.CColor color);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColor/InsertObj", ReplyAction="http://tempuri.org/IColor/InsertObjResponse")]
        System.Threading.Tasks.Task InsertObjAsync(RF.VehicleTracker.UIService.ColorReference.CColor color);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColor/GetColors", ReplyAction="http://tempuri.org/IColor/GetColorsResponse")]
        System.Collections.Generic.List<RF.VehicleTracker.UIService.ColorReference.CColor> GetColors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColor/GetColors", ReplyAction="http://tempuri.org/IColor/GetColorsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<RF.VehicleTracker.UIService.ColorReference.CColor>> GetColorsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColor/Insert", ReplyAction="http://tempuri.org/IColor/InsertResponse")]
        void Insert(string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColor/Insert", ReplyAction="http://tempuri.org/IColor/InsertResponse")]
        System.Threading.Tasks.Task InsertAsync(string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColor/Update", ReplyAction="http://tempuri.org/IColor/UpdateResponse")]
        void Update(System.Guid id, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColor/Update", ReplyAction="http://tempuri.org/IColor/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(System.Guid id, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColor/Delete", ReplyAction="http://tempuri.org/IColor/DeleteResponse")]
        void Delete(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColor/Delete", ReplyAction="http://tempuri.org/IColor/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColor/GetById", ReplyAction="http://tempuri.org/IColor/GetByIdResponse")]
        RF.VehicleTracker.UIService.ColorReference.CColor GetById(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColor/GetById", ReplyAction="http://tempuri.org/IColor/GetByIdResponse")]
        System.Threading.Tasks.Task<RF.VehicleTracker.UIService.ColorReference.CColor> GetByIdAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColor/UpdateObj", ReplyAction="http://tempuri.org/IColor/UpdateObjResponse")]
        void UpdateObj(RF.VehicleTracker.UIService.ColorReference.CColor color);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColor/UpdateObj", ReplyAction="http://tempuri.org/IColor/UpdateObjResponse")]
        System.Threading.Tasks.Task UpdateObjAsync(RF.VehicleTracker.UIService.ColorReference.CColor color);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColor/DeleteObj", ReplyAction="http://tempuri.org/IColor/DeleteObjResponse")]
        void DeleteObj(RF.VehicleTracker.UIService.ColorReference.CColor color);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IColor/DeleteObj", ReplyAction="http://tempuri.org/IColor/DeleteObjResponse")]
        System.Threading.Tasks.Task DeleteObjAsync(RF.VehicleTracker.UIService.ColorReference.CColor color);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IColorChannel : RF.VehicleTracker.UIService.ColorReference.IColor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ColorClient : System.ServiceModel.ClientBase<RF.VehicleTracker.UIService.ColorReference.IColor>, RF.VehicleTracker.UIService.ColorReference.IColor {
        
        public ColorClient() {
        }
        
        public ColorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ColorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ColorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ColorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertObj(RF.VehicleTracker.UIService.ColorReference.CColor color) {
            base.Channel.InsertObj(color);
        }
        
        public System.Threading.Tasks.Task InsertObjAsync(RF.VehicleTracker.UIService.ColorReference.CColor color) {
            return base.Channel.InsertObjAsync(color);
        }
        
        public System.Collections.Generic.List<RF.VehicleTracker.UIService.ColorReference.CColor> GetColors() {
            return base.Channel.GetColors();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<RF.VehicleTracker.UIService.ColorReference.CColor>> GetColorsAsync() {
            return base.Channel.GetColorsAsync();
        }
        
        public void Insert(string description) {
            base.Channel.Insert(description);
        }
        
        public System.Threading.Tasks.Task InsertAsync(string description) {
            return base.Channel.InsertAsync(description);
        }
        
        public void Update(System.Guid id, string description) {
            base.Channel.Update(id, description);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(System.Guid id, string description) {
            return base.Channel.UpdateAsync(id, description);
        }
        
        public void Delete(System.Guid id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(System.Guid id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public RF.VehicleTracker.UIService.ColorReference.CColor GetById(System.Guid id) {
            return base.Channel.GetById(id);
        }
        
        public System.Threading.Tasks.Task<RF.VehicleTracker.UIService.ColorReference.CColor> GetByIdAsync(System.Guid id) {
            return base.Channel.GetByIdAsync(id);
        }
        
        public void UpdateObj(RF.VehicleTracker.UIService.ColorReference.CColor color) {
            base.Channel.UpdateObj(color);
        }
        
        public System.Threading.Tasks.Task UpdateObjAsync(RF.VehicleTracker.UIService.ColorReference.CColor color) {
            return base.Channel.UpdateObjAsync(color);
        }
        
        public void DeleteObj(RF.VehicleTracker.UIService.ColorReference.CColor color) {
            base.Channel.DeleteObj(color);
        }
        
        public System.Threading.Tasks.Task DeleteObjAsync(RF.VehicleTracker.UIService.ColorReference.CColor color) {
            return base.Channel.DeleteObjAsync(color);
        }
    }
}
